'use client';

import React, { useState, useRef, useEffect } from 'react';
import {
  UploadCloud,
  Camera,
  Image as ImageIcon,
  X,
  FileCheck,
  User,
  Calendar,
  CreditCard,
  Building,
  ShieldAlert,
  Sparkles,
  RefreshCw,
  AlertCircle,
  HelpCircle,
} from 'lucide-react';
import { IdType, VerificationResponse } from '@/types';
import { PipelineProgress } from './PipelineProgress';
import { VerificationResult } from './VerificationResult';
import { WebcamModal } from './WebcamModal';
import { generateSyntheticCard } from '@/utils/cardGenerator';

export interface FormValues {
  name: string;
  dob: string;
  idNumber: string;
  institution: string;
  idType: IdType;
  minAge: number;
  eventDate: string;
}

interface VerificationFormProps {
  initialValues?: FormValues;
  initialFile?: File | null;
  onVerificationComplete?: (record: any) => void;
  onNavigateToAudit?: () => void;
}

export function VerificationForm({
  initialValues,
  initialFile,
  onVerificationComplete,
  onNavigateToAudit,
}: VerificationFormProps) {
  const [formData, setFormData] = useState<FormValues>({
    name: initialValues?.name || 'Rahul Kumar',
    dob: initialValues?.dob || '2005-03-14',
    idNumber: initialValues?.idNumber || 'ABC20261023',
    institution: initialValues?.institution || 'ABC Institute of Technology',
    idType: initialValues?.idType || 'COLLEGE_ID',
    minAge: initialValues?.minAge ?? 18,
    eventDate: initialValues?.eventDate || '2026-09-18',
  });

  const [documentFile, setDocumentFile] = useState<File | null>(initialFile || null);
  const [docPreviewUrl, setDocPreviewUrl] = useState<string | null>(null);

  const [selfieFile, setSelfieFile] = useState<File | null>(null);
  const [selfiePreviewUrl, setSelfiePreviewUrl] = useState<string | null>(null);

  const [isWebcamOpen, setIsWebcamOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [result, setResult] = useState<VerificationResponse | null>(null);

  const docInputRef = useRef<HTMLInputElement>(null);
  const selfieInputRef = useRef<HTMLInputElement>(null);

  // Sync initial values if changed from outside (e.g. preset preloader)
  useEffect(() => {
    if (initialValues) {
      setFormData(initialValues);
    }
  }, [initialValues]);

  useEffect(() => {
    if (initialFile) {
      setDocumentFile(initialFile);
      const url = URL.createObjectURL(initialFile);
      setDocPreviewUrl(url);
      return () => URL.revokeObjectURL(url);
    }
  }, [initialFile]);

  // Handle Document File Change
  const handleDocChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setDocumentFile(file);
      if (docPreviewUrl) URL.revokeObjectURL(docPreviewUrl);
      setDocPreviewUrl(URL.createObjectURL(file));
      setErrorMsg(null);
    }
  };

  // Handle Selfie File Change
  const handleSelfieChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setSelfieFile(file);
      if (selfiePreviewUrl) URL.revokeObjectURL(selfiePreviewUrl);
      setSelfiePreviewUrl(URL.createObjectURL(file));
    }
  };

  const clearDoc = () => {
    setDocumentFile(null);
    if (docPreviewUrl) URL.revokeObjectURL(docPreviewUrl);
    setDocPreviewUrl(null);
    if (docInputRef.current) docInputRef.current.value = '';
  };

  const clearSelfie = () => {
    setSelfieFile(null);
    if (selfiePreviewUrl) URL.revokeObjectURL(selfiePreviewUrl);
    setSelfiePreviewUrl(null);
    if (selfieInputRef.current) selfieInputRef.current.value = '';
  };

  // Generate a default sample card if user hasn't uploaded one
  const handleAutoGenerateDoc = async () => {
    try {
      const cardFile = await generateSyntheticCard({
        name: formData.name || 'Rahul Kumar',
        dob: formData.dob || '2005-03-14',
        idNumber: formData.idNumber || 'ABC20261023',
        institution: formData.institution || 'ABC Institute of Technology',
        idType: formData.idType,
      });
      setDocumentFile(cardFile);
      if (docPreviewUrl) URL.revokeObjectURL(docPreviewUrl);
      setDocPreviewUrl(URL.createObjectURL(cardFile));
      setErrorMsg(null);
    } catch {
      setErrorMsg('Failed to auto-generate sample document ID.');
    }
  };

  // Submit Handler
  const handleSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setErrorMsg(null);

    // Validation
    if (!formData.name.trim()) {
      setErrorMsg('Please enter the participant full name.');
      return;
    }
    if (!formData.dob) {
      setErrorMsg('Please enter date of birth.');
      return;
    }

    let fileToUpload = documentFile;
    if (!fileToUpload) {
      // Auto generate document on the fly if user clicks submit without uploading
      try {
        fileToUpload = await generateSyntheticCard({
          name: formData.name,
          dob: formData.dob,
          idNumber: formData.idNumber,
          institution: formData.institution,
          idType: formData.idType,
        });
        setDocumentFile(fileToUpload);
        setDocPreviewUrl(URL.createObjectURL(fileToUpload));
      } catch {
        setErrorMsg('Document ID image is required. Please upload or auto-generate one.');
        return;
      }
    }

    setIsLoading(true);
    setResult(null);

    try {
      const formPayload = new FormData();
      formPayload.append('name', formData.name);
      formPayload.append('dob', formData.dob);
      formPayload.append('id_number', formData.idNumber);
      formPayload.append('institution', formData.institution);
      formPayload.append('id_type', formData.idType);
      formPayload.append('min_age', formData.minAge.toString());
      formPayload.append('event_date', formData.eventDate);
      formPayload.append('file', fileToUpload, fileToUpload.name || 'document_id.jpg');

      if (selfieFile) {
        formPayload.append('selfie', selfieFile, selfieFile.name || 'selfie.jpg');
      }

      // Allow pipeline animation to run smoothly
      const [response] = await Promise.all([
        fetch('http://localhost:8000/api/verify', {
          method: 'POST',
          body: formPayload,
        }),
        new Promise((r) => setTimeout(r, 1800)),
      ]);

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || errorData.detail || `Server returned error ${response.status}`);
      }

      const data: VerificationResponse = await response.json();
      setResult(data);

      if (onVerificationComplete) {
        onVerificationComplete(data);
      }
    } catch (err: any) {
      setErrorMsg(err.message || 'Failed to complete verification. Check if backend is running on port 8000.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleReset = () => {
    setResult(null);
    setErrorMsg(null);
  };

  return (
    <div className="space-y-8">
      {/* Active Pipeline Animation Indicator */}
      <PipelineProgress isLoading={isLoading} />

      {/* Result Card when verification has finished */}
      {result && !isLoading && (
        <VerificationResult
          result={result}
          onNavigateToAudit={onNavigateToAudit}
          onReset={handleReset}
        />
      )}

      {/* Main Verification Input Form */}
      {(!result || isLoading) && (
        <form
          onSubmit={handleSubmit}
          className="rounded-2xl border border-slate-800 bg-slate-900/60 backdrop-blur-md p-6 sm:p-8 shadow-xl space-y-8"
        >
          {/* Form Header */}
          <div className="border-b border-slate-800 pb-5">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
                  <FileCheck className="h-5 w-5 text-cyan-400" />
                  Participant Verification Flow
                </h2>
                <p className="text-xs text-slate-400 mt-1">
                  Upload identity credentials for multi-gate OCR, tamper forensics, and duplicate screening.
                </p>
              </div>
              <button
                type="button"
                onClick={handleAutoGenerateDoc}
                className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-cyan-950/60 hover:bg-cyan-900/70 border border-cyan-700/50 text-cyan-300 text-xs font-semibold transition-colors"
                title="Generates a mock identity card directly in your browser"
              >
                <Sparkles className="h-3.5 w-3.5 text-cyan-400" />
                <span>Auto-Generate Sample ID</span>
              </button>
            </div>
          </div>

          {/* Error Banner */}
          {errorMsg && (
            <div className="flex items-center gap-2 p-3.5 rounded-xl bg-rose-950/50 border border-rose-800/80 text-rose-200 text-xs animate-shake">
              <AlertCircle className="h-4 w-4 shrink-0 text-rose-400" />
              <span>{errorMsg}</span>
            </div>
          )}

          {/* Section 1: Participant Metadata Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {/* Full Name */}
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300 flex items-center gap-1.5">
                <User className="h-3.5 w-3.5 text-slate-400" />
                Full Name <span className="text-rose-400">*</span>
              </label>
              <input
                type="text"
                required
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                placeholder="e.g. Rahul Kumar"
                className="w-full bg-slate-950/70 border border-slate-800 focus:border-cyan-500 rounded-xl px-3.5 py-2.5 text-sm text-white placeholder:text-slate-600 outline-none transition-all"
              />
            </div>

            {/* Date of Birth */}
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300 flex items-center gap-1.5">
                <Calendar className="h-3.5 w-3.5 text-slate-400" />
                Date of Birth <span className="text-rose-400">*</span>
              </label>
              <input
                type="date"
                required
                value={formData.dob}
                onChange={(e) => setFormData({ ...formData, dob: e.target.value })}
                className="w-full bg-slate-950/70 border border-slate-800 focus:border-cyan-500 rounded-xl px-3.5 py-2.5 text-sm text-white outline-none transition-all"
              />
            </div>

            {/* ID Number */}
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300 flex items-center gap-1.5">
                <CreditCard className="h-3.5 w-3.5 text-slate-400" />
                Document / ID Number
              </label>
              <input
                type="text"
                value={formData.idNumber}
                onChange={(e) => setFormData({ ...formData, idNumber: e.target.value })}
                placeholder="e.g. ABC20261023"
                className="w-full bg-slate-950/70 border border-slate-800 focus:border-cyan-500 rounded-xl px-3.5 py-2.5 text-sm text-white placeholder:text-slate-600 outline-none font-mono transition-all"
              />
            </div>

            {/* Institution / College */}
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300 flex items-center gap-1.5">
                <Building className="h-3.5 w-3.5 text-slate-400" />
                Institution / Organization
              </label>
              <input
                type="text"
                value={formData.institution}
                onChange={(e) => setFormData({ ...formData, institution: e.target.value })}
                placeholder="e.g. ABC Institute of Technology"
                className="w-full bg-slate-950/70 border border-slate-800 focus:border-cyan-500 rounded-xl px-3.5 py-2.5 text-sm text-white placeholder:text-slate-600 outline-none transition-all"
              />
            </div>

            {/* Document Type */}
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300 flex items-center gap-1.5">
                Document Type
              </label>
              <select
                value={formData.idType}
                onChange={(e) => setFormData({ ...formData, idType: e.target.value as IdType })}
                className="w-full bg-slate-950/70 border border-slate-800 focus:border-cyan-500 rounded-xl px-3.5 py-2.5 text-sm text-white outline-none transition-all cursor-pointer"
              >
                <option value="COLLEGE_ID">Student / College ID Card</option>
                <option value="AADHAAR">Aadhaar Card (UIDAI)</option>
                <option value="PAN">PAN Card (Income Tax Dept)</option>
                <option value="PASSPORT">Passport</option>
                <option value="DRIVING_LICENSE">Driving License</option>
              </select>
            </div>

            {/* Min Age & Event Date Policy */}
            <div className="grid grid-cols-2 gap-2">
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Min Age</label>
                <input
                  type="number"
                  min="1"
                  max="99"
                  value={formData.minAge}
                  onChange={(e) => setFormData({ ...formData, minAge: parseInt(e.target.value) || 18 })}
                  className="w-full bg-slate-950/70 border border-slate-800 focus:border-cyan-500 rounded-xl px-3.5 py-2.5 text-sm text-white outline-none font-mono transition-all"
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Event Date</label>
                <input
                  type="date"
                  value={formData.eventDate}
                  onChange={(e) => setFormData({ ...formData, eventDate: e.target.value })}
                  className="w-full bg-slate-950/70 border border-slate-800 focus:border-cyan-500 rounded-xl px-2.5 py-2.5 text-xs text-white outline-none transition-all"
                />
              </div>
            </div>
          </div>

          {/* Section 2: Uploaders (Document ID + Selfie) */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-2">
            {/* Document ID Card Uploader (Mandatory) */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-xs font-semibold text-white flex items-center gap-1.5">
                  <CreditCard className="h-4 w-4 text-cyan-400" />
                  Document ID Image <span className="text-rose-400">*</span>
                </label>
                {documentFile && (
                  <button
                    type="button"
                    onClick={clearDoc}
                    className="text-[11px] text-rose-400 hover:text-rose-300 flex items-center gap-1"
                  >
                    <X className="h-3.5 w-3.5" /> Remove
                  </button>
                )}
              </div>

              {docPreviewUrl ? (
                <div className="relative rounded-2xl overflow-hidden border border-cyan-500/40 bg-slate-950 group aspect-[16/10] flex items-center justify-center shadow-lg">
                  <img
                    src={docPreviewUrl}
                    alt="Document Preview"
                    className="w-full h-full object-contain p-2"
                  />
                  <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-3 backdrop-blur-xs">
                    <button
                      type="button"
                      onClick={() => docInputRef.current?.click()}
                      className="px-3 py-1.5 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-semibold transition-colors"
                    >
                      Replace
                    </button>
                    <button
                      type="button"
                      onClick={clearDoc}
                      className="px-3 py-1.5 rounded-lg bg-rose-600 hover:bg-rose-500 text-white text-xs font-semibold transition-colors"
                    >
                      Delete
                    </button>
                  </div>
                  <div className="absolute bottom-2 left-2 bg-black/70 px-2.5 py-1 rounded text-[11px] font-mono text-cyan-300 truncate max-w-[80%]">
                    {documentFile?.name} ({(documentFile?.size ? documentFile.size / 1024 : 0).toFixed(1)} KB)
                  </div>
                </div>
              ) : (
                <div
                  onClick={() => docInputRef.current?.click()}
                  className="rounded-2xl border-2 border-dashed border-slate-700 hover:border-cyan-500/80 bg-slate-950/40 hover:bg-slate-950/70 p-6 flex flex-col items-center justify-center text-center cursor-pointer transition-all aspect-[16/10]"
                >
                  <div className="h-12 w-12 rounded-xl bg-cyan-950/60 border border-cyan-800/60 text-cyan-400 flex items-center justify-center mb-3">
                    <UploadCloud className="h-6 w-6" />
                  </div>
                  <p className="text-xs font-semibold text-white mb-1">
                    Click to upload or drag & drop document
                  </p>
                  <p className="text-[11px] text-slate-500 max-w-xs mb-3">
                    Accepts JPG, PNG, WEBP (Student ID, Aadhaar, PAN)
                  </p>
                  <span className="text-[11px] font-mono text-cyan-400 underline hover:text-cyan-300">
                    Or click here to browse files
                  </span>
                </div>
              )}
              <input
                ref={docInputRef}
                type="file"
                accept="image/*"
                onChange={handleDocChange}
                className="hidden"
              />
            </div>

            {/* Selfie Biometric Verification (Optional) */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-xs font-semibold text-white flex items-center gap-1.5">
                  <Camera className="h-4 w-4 text-blue-400" />
                  Participant Selfie / Biometric Check
                  <span className="text-[10px] font-mono text-slate-500 font-normal">(Optional)</span>
                </label>
                {selfieFile && (
                  <button
                    type="button"
                    onClick={clearSelfie}
                    className="text-[11px] text-rose-400 hover:text-rose-300 flex items-center gap-1"
                  >
                    <X className="h-3.5 w-3.5" /> Remove
                  </button>
                )}
              </div>

              {selfiePreviewUrl ? (
                <div className="relative rounded-2xl overflow-hidden border border-blue-500/40 bg-slate-950 group aspect-[16/10] flex items-center justify-center shadow-lg">
                  <img
                    src={selfiePreviewUrl}
                    alt="Selfie Preview"
                    className="w-full h-full object-contain p-2"
                  />
                  <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-3 backdrop-blur-xs">
                    <button
                      type="button"
                      onClick={() => setIsWebcamOpen(true)}
                      className="px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold transition-colors"
                    >
                      Retake Camera
                    </button>
                    <button
                      type="button"
                      onClick={clearSelfie}
                      className="px-3 py-1.5 rounded-lg bg-rose-600 hover:bg-rose-500 text-white text-xs font-semibold transition-colors"
                    >
                      Delete
                    </button>
                  </div>
                  <div className="absolute bottom-2 left-2 bg-black/70 px-2.5 py-1 rounded text-[11px] font-mono text-blue-300">
                    Selfie attached ({(selfieFile?.size ? selfieFile.size / 1024 : 0).toFixed(1)} KB)
                  </div>
                </div>
              ) : (
                <div className="rounded-2xl border-2 border-dashed border-slate-700 bg-slate-950/40 p-6 flex flex-col items-center justify-center text-center aspect-[16/10]">
                  <div className="h-12 w-12 rounded-xl bg-blue-950/60 border border-blue-800/60 text-blue-400 flex items-center justify-center mb-3">
                    <Camera className="h-6 w-6" />
                  </div>
                  <p className="text-xs font-semibold text-white mb-2">
                    Face match against document photo
                  </p>
                  <div className="flex items-center gap-2">
                    <button
                      type="button"
                      onClick={() => setIsWebcamOpen(true)}
                      className="px-3 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold transition-colors flex items-center gap-1.5 shadow-md shadow-blue-600/20"
                    >
                      <Camera className="h-3.5 w-3.5" />
                      <span>Take Live Selfie</span>
                    </button>
                    <button
                      type="button"
                      onClick={() => selfieInputRef.current?.click()}
                      className="px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium transition-colors"
                    >
                      Upload File
                    </button>
                  </div>
                </div>
              )}
              <input
                ref={selfieInputRef}
                type="file"
                accept="image/*"
                onChange={handleSelfieChange}
                className="hidden"
              />
            </div>
          </div>

          {/* Submit Action Button */}
          <div className="pt-2">
            <button
              type="submit"
              disabled={isLoading}
              className="w-full py-4 px-6 rounded-2xl bg-gradient-to-r from-cyan-600 via-blue-600 to-indigo-600 hover:from-cyan-500 hover:to-indigo-500 text-white font-bold text-base shadow-xl shadow-cyan-600/25 transition-all flex items-center justify-center gap-3 disabled:opacity-50 cursor-pointer"
            >
              {isLoading ? (
                <>
                  <RefreshCw className="h-5 w-5 animate-spin" />
                  <span>Evaluating Verification Gates...</span>
                </>
              ) : (
                <>
                  <ShieldAlert className="h-5 w-5" />
                  <span>Run VeriForge Verification Flow</span>
                </>
              )}
            </button>
          </div>
        </form>
      )}

      {/* Webcam Modal */}
      <WebcamModal
        isOpen={isWebcamOpen}
        onClose={() => setIsWebcamOpen(false)}
        onCapture={(file) => {
          setSelfieFile(file);
          if (selfiePreviewUrl) URL.revokeObjectURL(selfiePreviewUrl);
          setSelfiePreviewUrl(URL.createObjectURL(file));
        }}
      />
    </div>
  );
}
